name: Release LowDB - Static Library

on:
  workflow_dispatch:
    inputs:
        tag_name:
          description: "Tag name for the release"
          required: true
          default: "v0.0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build library
        run: |
          chmod +x ./build.sh && ./build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: lowdb ${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
